spring.application.name=review-microservice

server.port=9092

spring.datasource.url=jdbc:mysql://192.168.0.205:3306/review_micro3?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMuliQueries=true&useSSL=false&allowPublicKeyRetrivel=true
spring.datasource.username=smeface_dev
spring.datasource.password=Password!3212
spring.datasource.driver-class-name=com.mysql.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:9093/eureka

#spring.config.import=configserver:http://localhost:8888